Revert "github: run flake checks"
This reverts commit 1dfea2c44eed2bb7e40e69a887cb76a87a5af9fa.

The machine used doesn't seem to be supported.
  error: a 'x86_64-linux' with features {kvm, nixos-test} is required to build '/nix/store/rcnffq6qs0dg2in42x84a9gmcrfhz4yz-vm-test-run-unnamed.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, nixos-test}